### ISSUE TITLE
How is takeWhile different from filter?

### ISSUE THREAD

**Issue by kirbysayshi** [cognitect-labs/transducers-js#17]
`takeWhile` seems to [check the predicate](https://github.com/cognitect-labs/transducers-js/blob/2575c45ae828fe46590bf0b1b989f9f628d1275a/src/com/cognitect/transducers.js#L403), but I assumed that once the predicate returned non-true, it would forever ignore subsequent values. If you had input like `[0, 1, 2, 3, 4, 3, 2, 1]`, you'd get `[0, 1, 2, 2, 1]` (using `return n < 3`).

Is takeWhile meant to be an alias for filter?

**Comment by uwo** [comment]
As you point out, `takeWhile` will terminate early (return a "reduced" value) if the predicate evaluates to true, while `filter` continues processing.

**Comment by kirbysayshi** [comment]
Ah yes. Sorry for missing that! I was still getting used to the lifecycle
of transducers when I posted.
