### ISSUE TITLE
Why is the immutable-js demo broken?

### ISSUE THREAD

**Issue by gilbox** [cognitect-labs/transducers-js#19]
I'm trying to figure out how to use this library with immutable-js, but the [immutable-js demo](https://github.com/cognitect-labs/transducers-js#immutable-js) in the README **[is broken](http://jsbin.com/losiqi/1/edit?js,console)** [jsbin]. Any ideas why it's broken?

**Comment by swannodette** [comment]
hrm dunno, will look into it tomorrow.

**Comment by swannodette** [comment]
Cannot reproduce. Seems to work fine, I've included a simple test to master.

**Comment by gilbox** [comment]
:+1: My jsbin seems to be working now.

(btw, is it tomorrow already?  :P )

**Comment by swannodette** [comment]
@gilbox haha, glad to hear it. Yeah got busy :)
