### ISSUE TITLE
Direction of functional composition with toFn?

### ISSUE THREAD

**Issue by wcourtney** [cognitect-labs/transducers-js#22]
The function `comp` for functional composition is applied using reverse ordering when used with the `toFn()` function.

I would _expect_ that `comp(f,g)` would result in a function `f(g(x))`, as confirmed in the example given for the function:
```js
var inc = function(n) { return n + 1 };
var double = function(n) { return n * 2 };
var incDouble = t.comp(double, inc);
incDouble(3); // 8
```

However, looking at the ```toFn``` function, the doc example (and experimentation) provide a result as `g(f(x))`:
```js
var arr = [0,1,2,3,4,5],
var apush = function(arr, x) { arr.push(x); return arr; },
var xf = t.comp(t.map(inc),t.filter(isEven));
arr.reduce(t.toFn(xf, apush), []); // [2,4,6]
```
Were the composition consistent with the first example, the expected result of composing the mapping of increment to the even values of the input array should always be an array of exclusively _odd_ values. Instead, it appears that we are filtering the even values of the incremented input array, i.e. it looks more like we should expect from `t.comp(t.filter(isEven), t.map(inc))`.

**Comment by dchelimsky** [comment]
Your observation is correct. See "Defining Transformations With Transducers" on http://clojure.org/transducers for details.

**Comment by wcourtney** [comment]
Thanks for the confirmation. I found a more detailed explanation [here](http://isaaccambron.com/blog/2014/12/13/transducer-composition.html) in case anyone else seeing this is interested.
