### ISSUE TITLE
Curring "into" method, will duplicate list elements 

### ISSUE THREAD

**Issue by marcog83** [cognitect-labs/transducers-js#26]
Hi, I'm using transducer to transform an array from A to B. Source data is from a Promise, so, in order to keep code simple, I curried the "into" method. 
The problem is that when I call the curried function more than once, the resulting list grows with duplicated elements.

this is my code
``` javascript
function Model(){
    //first i define the curried function
    var mapResults = curry(t.into)([], xf); 
    return{
         load:()=>asyncFetch(request).then(mapResults)
    }
}
//then later I call the load method
var m=Model();
m.load()
```

Looking at the transducer code, I saw that `into` method has this piece of code

``` javascript
if (com.cognitect.transducers.isArray(a)) {
    return com.cognitect.transducers.transduce(b, com.cognitect.transducers.arrayPush, a, c);
  }
```
`a` variable is the initial array. but in the curried version, it is always the same. So I changed `a` to `a.slice(0)` in order to create a copy of it.

Sorry for my english,
hope it can help.
marco

**Comment by swannodette** [comment]
Thanks for the report, but this is not a bug. You should not curry mutable arguments.

**Comment by marcog83** [comment]
Ok, got it, I though `a` was immutable. just to know, i changed my function

```javascript
var mapResults = initial=>  curry( t.into)(initial, xf)

load:()=>asyncFetch(request).then(mapResults([]))
```
