### ISSUE TITLE
Exports typo

### ISSUE THREAD

**Issue by Chris-Andrews** [cognitect-labs/transducers-js#27]
I think there is a typo in the exports of transducers.js:

```javascript
            keep: transducers.keep,
            Kemove: transducers.Keep,
```
should likely be:
```javascript
            keep: transducers.keep,
            Keep: transducers.Keep,
```

**Comment by swannodette** [comment]
fixed https://github.com/cognitect-labs/transducers-js/commit/772804bbc32d5a642cd4df6c27937b0e12689f6a
