### ISSUE TITLE
How to implement the protocol?

### ISSUE THREAD

**Issue by joneshf** [cognitect-labs/transducers-js#28]
I have the following object:

```js
function Identity(x) {
  if (!(this instanceof Identity)) {
    return new Identity(x);
  };

  this.runIdentity = function() {
    return x;
  };
}

Identity.prototype.map = function(f) {
  return Identity(f(this.runIdentity()));
};

Identity.prototype.toString = function() {
  return 'Identity(' + this.runIdentity().toString() + ')';
};
```

And I cannot figure out how to implement the transducers protocol.

I've tried the following:

```js
Identity.prototype['@@transducer/init'] = function() {
  return this;
};

Identity.prototype['@@transducer/result'] = function(x) {
  return x;
};

Identity.prototype['@@transducer/step'] = function(_, y) {
  return Identity(y);
};
```

But then when I try to use it, it doesn't produce the output I'd expect:

```js
var inc = function(n) { return n + 1; };

console.log('%s', t.into([], t.map(inc), Identity(3)));
```

```
➜  ~  node identity.js 
runIdentity,function () {
    return x;
  }1
```

It looks like it's creating the array, but putting the wrong values into it.

If I try to use an `Identity` as the thing to build stuff into, then I wind up with more unexpected behavior:

```js
console.log('%s', t.into(Identity(0), t.map(inc), Identity(3)));
```

```
➜  ~  node identity.js
Identity(0)
```
It looks like it's ignoring the input, and just returning the thing to build into.

Can anyone provide some insight as to what is going on here? I feel like I cannot understand what the protocol wants, and that's what is causing my issues here.

**Comment by swannodette** [comment]
This is a question not an issue.

**Comment by joneshf** [comment]
My "issue" is that I can't understand the protocol and need more information. After discussing it with many other people, they have similar conclusions. You can view it as a question if you desire, but the point is that some things are unclear in the protocol for many people, and we'd like clarification. Closing this without attempting to address my concerns doesn't help me in the slightest.

Where should questions be directed? There is no information on where to post questions in the readme, nothing on the wiki, and nothing stating that you should only open "issues", not "questions".

**Comment by dnalot** [comment]
I agree, question or otherwise, it begs at least a CC to someone with consideration to answer a fellow open source maintainer. @joneshf At first glance it appears `into` expects `iterable` collections in first ant last positions instead of `transformer`s. I didn't try but see @swannodette's [test](https://github.com/cognitect-labs/transducers-js/blob/2996f6b11d683d3a5752c45cfaec9fe86ac0eaa6/test/tests.js#L257-L271).
