### ISSUE TITLE
Where does the convention "at-at-slash" come from?

### ISSUE THREAD

**Issue by rstuven** [cognitect-labs/transducers-js#30]
As in `@@transducer/init`, for example. Just out of curiosity. 

I've recently seen this convention used in other libraries (eg. [here](https://github.com/michalkvasnicak/routex/blob/b641860bac60a6ad6a1754ae8b7e5ca5d859a97c/src/actionTypes.js) and [here](https://github.com/rackt/redux/blob/2c473534fcf27f80db4b7f1cb177efa007dfced1/src/createStore.js#L10)), but I saw it here first. I suppose it's a way of namespacing, but I couldn't find an explanation or explicit mention about it anywhere.

Thanks.

**Comment by swannodette** [comment]
Probably from urls? Also Clojure keywords are like this so probably my bias.

**Comment by dnalot** [comment]
@rstuven It comes from the [ES2015 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-well-known-symbols) (previously ES6 draft) referenced in #20 which @swannodette coordinated.
